name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, linux, android]  # labels on your runner
    timeout-minutes: 45

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            cmdline-tools;latest
            platforms;android-35
            build-tools;35.0.0

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble Debug variants
        run: ./gradlew --no-daemon --stacktrace assembleDebug

      - name: Unit tests & detekt (if configured)
        run: ./gradlew --no-daemon --stacktrace test detekt || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: debug-apks
          if-no-files-found: warn
          path: |
            **/build/outputs/**/*.apk
