name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: [self-hosted, ubuntu, android]
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Lint and Test
        run: ./gradlew ktlintCheck detekt lint test --stacktrace
      # - name: Upload SARIF (Android Lint)
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: app/build/reports/lint-results-debug.sarif

  assemble:
    runs-on: [self-hosted, ubuntu, android]
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Assemble APKs
        run: ./gradlew :app-mobile:assembleDebug :app-wear:assembleDebug --stacktrace
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            app-mobile/build/outputs/apk/debug/*.apk
            app-wear/build/outputs/apk/debug/*.apk

  # github-hosted-example:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: '21'
  #     - uses: gradle/actions/setup-gradle@v3
  #     - run: ./gradlew lint test

